name: CI CD

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the 'main' branch

permissions:
  contents: read
  actions: read

jobs:
  unit-test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out the repository code

      - name: Set up JDK 17
        uses: actions/setup-java@v3  # Set up JDK 17 using the Temurin distribution
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Test with Maven
        run: mvn test  # Test the project using Maven